### ISSUE TITLE
关于判断解析表情函数是否可用的逻辑

### ISSUE THREAD

**Issue by youranreus** [jrotty/CommentNotifier#10]
hello 泽泽，我的一个朋友正在使用这个插件，但是对最近的增加的解析主题表情的功能不太理解。

我看了一下这一部分的代码，发现是用了`function_exists`这个方法来判断主题的表情解析函数是否可用。有些主题可能会将解析函数通过类的静态方法实现（`XX::parseBiaoqing`），这样子可能就无法通过`function_exists`判断了。或许可以试试`is_callable`方法？

**Comment by jrotty** [comment]
接受建议改用is_callable了，原理其实很简单，正常主题表情都是用特殊格式文本进行输入的，然后主题表情函数将文本替换成img标签，进而输出评论内容。而这个插件就是需要用户将这个函数名填入进去，这样用户评论成功后，在发送邮件内容时也可以执行主题的这个函数进而替换评论内容

**Comment by youranreus** [comment]
嗯嗯，理解了。这个功能真的非常实用(‵▽′)
