### ISSUE TITLE
发现一个bug

### ISSUE THREAD

**Issue by LamaGE** [jrotty/CommentNotifier#11]
![屏幕截图 2023-04-26 135652](https://user-images.githubusercontent.com/6577423/234482626-93c47792-83c7-4fb6-aec9-0affcae7ded6.png)
![屏幕截图 2023-04-26 135800](https://user-images.githubusercontent.com/6577423/234482630-4b182950-b30d-4ea9-94cd-172e0b55ff1e.png)
我的typecho在[www.xxx.com/blog]下，启用这个插件以后，邮件可以正常收到。但是所有的信息都是空白。
检查了plugins，找到了sendmail()这个函数，测试，返回均空值。
是否存在网站启动目录的问题？邮件和模板都是可以正常了，只有是内容都是空白。

**Comment by jrotty** [comment]
异步提交那个关下试试

**Comment by LamaGE** [comment]
关闭了，发现可以了！多谢多谢！
















在 2023-04-26 14:49:32，"jrotty" ***@***.***> 写道：

异步提交那个关下试试
