### ISSUE TITLE
疑似不兼容typecho1.2.1，以及建议

### ISSUE THREAD

**Issue by TacKana** [jrotty/CommentNotifier#16]
bug:插件启用配置好之后无法发送邮件，无法输出log.txt文件，打开是空内容。
建议:在插件发信配置设置页面增加一个点击按钮，用于配置完邮箱信息后快速检查验证发信配置是否正确。

typecho版本：1.2.1
采用Icefox主题，版本: 1.7.3
已经启用的插件ShortLinks，CommentNotifier

**Comment by jrotty** [comment]
log.txt文件权限看看，是不是没有写入权限

**Comment by TacKana** [comment]
就是www755权限，貌似没问题，但是没办法发信，是阿里企业邮箱



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月11日(周四) 中午1:46
收件人: ***@***.***&gt;;
抄送: "new ***@***.******@***.***&gt;;
主题: Re: [jrotty/CommentNotifier] 疑似不兼容typecho1.2.1，以及建议 (Issue #16)




 
log.txt文件权限看看，是不是没有写入权限

**Comment by jrotty** [comment]
那就不清楚了，这个插件我是QQ邮箱，没有问题的

**Comment by TacKana** [comment]
主要是不能看打印出来的log,排查不了问题啊🙃



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月11日(周四) 中午1:49
收件人: ***@***.***&gt;;
抄送: "new ***@***.******@***.***&gt;;
主题: Re: [jrotty/CommentNotifier] 疑似不兼容typecho1.2.1，以及建议 (Issue #16)




 
那就不清楚了，这个插件我是QQ邮箱，没有问题的

**Comment by TacKana** [comment]
还是死活发不了,log.txt我设置777权限也不能写日志,但是相同的配置我自己手机上就可以正常登录邮箱发信，请问一下你的网站php是什么版本，有没有用什么php扩展呢？

**Comment by TacKana** [comment]
> 那就不清楚了，这个插件我是QQ邮箱，没有问题的

还是死活发不了,log.txt我设置777权限也不能写日志,但是相同的配置我自己手机上就可以正常登录邮箱发信，请问一下你的网站php是什么版本，有没有用什么php扩展呢？

**Comment by jrotty** [comment]
typecho1.2.1，php8.2，宝塔直接装的，没安装什么拓展

**Comment by jrotty** [comment]
要不你试试别人的插件

**Comment by TacKana** [comment]
> 要不你试试别人的插件

还是不行，不知道是什么玄学bug，有别的邮箱推送插件可以推荐一下吗？

**Comment by jrotty** [comment]
试试他的 https://github.com/soxft/CommentToMail

**Comment by TacKana** [comment]
> 试试他的 https://github.com/soxft/CommentToMail

好像找到问题了，是不是企业邮箱需要先验证一遍服务器才能够发信啊？推荐插件我试了可以正常使用，那就是你的插件有bug了

**Comment by jrotty** [comment]
能用他的就行，我这个因为自己用着没问题，也就懒得排查了

**Comment by TacKana** [comment]
你要小心QQ邮箱暴露你的源站IP哦



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月11日(周四) 下午3:47
收件人: ***@***.***&gt;;
抄送: "new ***@***.******@***.***&gt;;
主题: Re: [jrotty/CommentNotifier] 疑似不兼容typecho1.2.1，以及建议 (Issue #16)




 
能用他的就行，我这个因为自己用着没问题，也就懒得排查了

**Comment by jrotty** [comment]
ip早就暴露了，也经常被打，反正网站收入几乎没有，死就死吧😄
