### ISSUE TITLE
评论报错

### ISSUE THREAD

**Issue by ouyanglong721** [jrotty/CommentNotifier#17]
使用1.2.0版本typecho提示
Argument 1 passed to Utils\AutoP::parse() must be of the type string, null given, called in /app/var/Widget/Base/Comments.php on line 370

**Comment by jrotty** [comment]
这个路径不是插件的路径，不清楚啥原因，我1.2.1目前使用正常

或则你可以试试别人的插件比如这个： https://github.com/soxft/CommentToMail
