### ISSUE TITLE
大佬你好，请问下你的环境是什么？

### ISSUE THREAD

**Issue by hczcyy** [jrotty/CommentNotifier#19]
我在php7.4下开启异步没有作用，而开启会导致提交评论很慢

**Comment by jrotty** [comment]
其实我站貌似提交速度也不快，插件就是利用typecho本身提供的异步请求接口实现异步的，目前代码方面没有看出来啥毛病

**Comment by jrotty** [comment]
刚刚在代码中加入了条注释`//sleep(10);`，消除`//`后代码在发邮件前会沉睡10秒，可以用于测试异步是否生效，生效了提交评论的时候就不会被这个沉睡10秒的代码影响，我测试了下异步代码确实生效了

**Comment by hczcyy** [comment]
感谢大佬回复，我也去测试一下

**Comment by hczcyy** [comment]
> 刚刚在代码中加入了条注释`//sleep(10);`，消除`//`后代码在发邮件前会沉睡10秒，可以用于测试异步是否生效，生效了提交评论的时候就不会被这个沉睡10秒的代码影响，我测试了下异步代码确实生效了

另外还有一个问题，只有通过审核的评论才有邮件通知，待审核评论不会通知。

测试发现在后台将未审核评论点击通过时才发邮件，囧~我的想法是有人评论了还在待审核的时候给我发邮件。 ：）

**Comment by hczcyy** [comment]
我为我的无知道歉~确实发送了
