### ISSUE TITLE
大佬不知道为啥我的博客通知不生效😭

### ISSUE THREAD

**Issue by kuhehe** [jrotty/CommentNotifier#21]
大佬不知道为啥我的博客通知不生效😭

主题是我最近移植的，希望大佬可以看到的话，能否帮忙看看，谢谢！

我的博客地址：https://t.kuhehe.top/

也可以联系我的邮箱：kuhehe3075@qq.com
谢谢！

**Comment by jrotty** [comment]
发信方式选择传统方式试试，首先要确保你各项参数设置的没有问题

**Comment by BoyChai** [comment]
> 发信方式选择传统方式试试，首先要确保你各项参数设置的没有问题

我这边是测试邮件行 但是发送测试评论不通知

**Comment by BoyChai** [comment]
> > 发信方式选择传统方式试试，首先要确保你各项参数设置的没有问题
> 
> 我这边是测试邮件行 但是发送测试评论不通知

https://blog.boychai.xyz/
![image](https://github.com/user-attachments/assets/45c55311-f45d-4a10-821f-68921a7d00cb)
![image](https://github.com/user-attachments/assets/c38aa05a-5e1e-4205-9a1c-077934538c87)

**Comment by jrotty** [comment]
加我QQ吧485868654

**Comment by kuhehe** [comment]
现在好了，🙃🙃
