### ISSUE TITLE
请问为什么我的插件管理页面，操作那一列显示“即插即用”，没有设置选项

### ISSUE THREAD

**Issue by yingyu5658** [jrotty/CommentNotifier#22]
如题
![c](https://github.com/user-attachments/assets/6b43e96f-3f81-42b1-9867-5bf256a152e6)

**Comment by jrotty** [comment]
正常路径应该`/usr/plugin/CommentNotifier`然后里面是插件的一些文件，你的情况可能是`/usr/plugin`下面一堆插件文件

**Comment by yingyu5658** [comment]
破案了，刚发现我的typecho版本只有1.1。。。。。

**Comment by jrotty** [comment]
😄
