### ISSUE TITLE
网站源IP会泄露，能否加一个阿里邮箱的选项

### ISSUE THREAD

**Issue by mcyydscc** [jrotty/CommentNotifier#6]
刚才测试了一下，如果网站有CDN，使用这个插件发送邮件会泄露源IP，因此我觉得可以增加一个阿里邮箱的选项，有了用户的Accesskey后使用阿里的服务器发送，就不会泄露源IP
![image](https://user-images.githubusercontent.com/90653809/212291770-88a77bcc-5568-48a6-bd3f-a6931ced1e80.png)

**Comment by jrotty** [comment]
1.4.0版本发布了，已经支持了，欢迎测试
