### ISSUE TITLE
发出的邮件标题和评论内容都为空

### ISSUE THREAD

**Issue by bluefo** [jrotty/CommentNotifier#9]
感谢分享这么实用的插件！

插件1.4.3版本
使用内置模板没有修改，typecho后台没有开启评论审核，游客可以直接评论。

邮件可以正常收到，但是收到的邮件中获取不到文章标题和评论内容，请问是否是我配置错误？

邮件的标题：文章《》有条待审评论

邮件的内容：
bluefo 需审评论 
在   bluefo 有新的评论需审核 
在《》文章中待审核评论如下: 
此致  bluefo

谢谢您！

**Comment by jrotty** [comment]
关闭 异步提交 功能应该就可以了，这个不兼容ajax提交评论的
